USE SCHEMA DEMO;
create or replace TABLE UNIT_OF_MEASURE (
	MATERIALNUMBER VARCHAR(50),
	TOUOM VARCHAR(3),
	FROMUOM VARCHAR(3),
	NUMERATORFORCONVTOBASEUOM VARCHAR(50),
	DENOMINATORFORCONVTOBASEUOM VARCHAR(50),
	LENGTH VARCHAR(50),
	WIDTH VARCHAR(50),
	HEIGHT VARCHAR(50),
	VOLUME VARCHAR(50),
	GROSSWEIGHT VARCHAR(50),
	WEIGHTUNIT VARCHAR(3),
	INTERNALCHARACTERISTIC VARCHAR(10),
	UOMSORTNUMBER VARCHAR(2),
	REMAININGVOLUMEAFTERNESTING VARCHAR(50),
	MAXSTACKINGFACTOR VARCHAR(50),
	MAXTOPLOADONFULLPACKAGE VARCHAR(50),
	CAPACITYUSAGE VARCHAR(50),
	CONVERSIONFACTOR FLOAT,
	DATASOURCE VARCHAR(10),
	UPDATEDON TIMESTAMP_NTZ(9)
);