USE SCHEMA DEMO;
create or replace TABLE PURCHASING_GROUPS (
	CLIENT NUMBER(10,0),
	PURCHASINGGROUP VARCHAR(10),
	PURCHASINGGROUPDESC VARCHAR(100),
	PURCHASINGGROUPTEL VARCHAR(100),
	OUTPUTDEVICE VARCHAR(10),
	PURCHASINGGROUPFAX VARCHAR(100),
	TELEPHONENO VARCHAR(20),
	TELEPHONEEXTENSION VARCHAR(10),
	EMAILADDRESS VARCHAR(100),
	LANDINGFILETIMESTAMP VARCHAR(50),
	UPDATEDON TIMESTAMP_NTZ(9),
	DATASOURCE VARCHAR(10)
);