USE SCHEMA DEMO;
create or replace TABLE MATERIAL_CPN_MPN (
	CLIENT NUMBER(38,0),
	MATERIALNUMBER VARCHAR(50),
	CUSTOMERPARTNUMBER VARCHAR(50),
	MANUFACTURERNAME VARCHAR(100),
	MANUFACTURINGPARTNUMBER VARCHAR(100),
	CUSTOMERNAMEFROMAGILE VARCHAR(100),
	AGILEREVISION VARCHAR(20),
	REVISIONLEVEL VARCHAR(5),
	COPYEXACTFLAG VARCHAR(5),
	CRITICALPARTFLAG VARCHAR(5),
	SUPPLIERLOCKEDFLAG VARCHAR(5),
	PREFERREDFLAGFORMPN VARCHAR(5),
	DATEONWHICHTHERECORDWASCREATED VARCHAR(50),
	MATERIALFLAGGEDASUMC VARCHAR(50),
	PARTTYPE VARCHAR(50),
	INTERNALREVISIONINDICATOR VARCHAR(50),
	SUBORDINATEFLAG VARCHAR(50),
	AGILERELEASETYPE VARCHAR(50),
	UPDATEDON TIMESTAMP_NTZ(9),
	DATASOURCE VARCHAR(16777216)
);