USE SCHEMA DEMO;
create or replace TABLE COMMODITYCODE (
	COMMODITYCODETIER1 VARCHAR(100),
	COMMODITYCODETIER2 VARCHAR(100),
	SUBCOMMODITYCODE VARCHAR(100),
	COMMODITYCODESAP VARCHAR(100),
	UPDATEDON TIMESTAMP_NTZ(9),
	DATASOURCE VARCHAR(50)
);